# You can use globbing.
symlinks:
  # These files will be linked directly to ~.
  default:
    - vim
    - vim/vimrc
    - vim/gvimrc
    - zsh/zshrc
    - zsh/zshenv
    - tmux/tmux.conf
    - git/gitconfig
    - misc/*
  development:
    - ruby/gemrc
    - ruby/rspec
    - ruby/rubocop.yml
    - javascript/*

  # In these hash, the keys are the source links and the values are the
  # destination links. You cannot use globbing nor environment variables, but you
  # can use ~ at the beginning of a string.
  custom:
    keyremap4macbook/private.xml: ~/Library/Application Support/KeyRemap4MacBook/private.xml
    ruby/rvm-global.gems: ~/.rvm/gemsets/global.gems

# Directories to create when running the corresponding rake task.
# If these directories already exist, they won't be overridden.
directories_to_create:
  - ~/Code
  - ~/tmp
  - ~/.ssh
