#!/bin/sh

# Define some colors.
COL="\033[1;31m"
END="\033[0m"



# If you're on a Mac and you haven't installed Xcode, exit.
if [[ "$(uname)" == "Darwin" && ! -d '/Applications/Xcode.app' ]]; then
  echo -e "${COL}You don't have Xcode installed in /Applications/Xcode.app. Install it and try again.${END}"
  return 1
fi



# Oh My Zsh
echo -e "${COL}Installing oh-my-zsh${END}"
curl -L http://install.ohmyz.sh | sh
echo ''

# RVM for the rubiess
echo -e "${COL}Installing RVM${END}"
curl -L https://get.rvm.io | sh -s stable
echo ''

# For the c alias (syntax highlighted cat)
echo -e "${COL}Installing Pygments (for the 'c' alias) - this needs sudo${END}"
sudo easy_install Pygments
echo ''

if [[ "$(uname)" == "Darwin" ]]; then
  # Mac setup
  echo -e "${COL}Installing Apple's developer tools${END}"
  xcode-select --install
  echo ''

  echo 'Wait for the xcode-select installation to finish. Continue? [yn] '
  read DONE
  [[ "$DONE" == 'n' ]] && return 1


  echo -e "${COL}Installing Homebrew${END}"
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  echo ''

  echo -e "${COL}Installing git in order to clone dotfiles${END}"
  brew install git
  echo ''

  echo -e "${COL}Temporarely adding /usr/local/bin to the \$PATH${END}"
  PATH="/usr/local/bin:$PATH"
  echo ''

  echo -e "${COL}Cloning dotfiles from GitHub${END}"
  git clone https://github.com/whatyouhide/dotfiles.git ~/.dotfiles
  echo ''

  echo -e "${COL}Be sure to reload your shell in order to see changes${END}"
  echo 'Also be sure to execute rake symlink and the rake setup:* tasks from ~/.dotfiles'

else
  # We're on Linux

  echo -e "${COL}I believe you're on Linux. If that is true, first install git and then:"
  echo '  git clone https://github.com/whatyouhide/dotfiles.git ~/.dotfiles'
  echo 'Also be sure to execute rake symlink and the rake setup:* tasks from ~/.dotfiles'
fi
