#!/bin/sh

# Oh My Zsh
curl -L http://install.ohmyz.sh | sh

# rvm for the rubiess
curl -L https://get.rvm.io | bash -s stable

# z, oh how I love you
git clone https://github.com/rupa/z.git $HOME/.z-code
chmod +x $HOME/.z/z.sh
# also consider moving over your current .z file if possible. it's painful to rebuild :)

# for the c alias (syntax highlighted cat)
sudo easy_install Pygments

# Homebrew
if [[ "$(~/.dotfiles/bin/which-os)" == "mac" ]]; then
  ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)
fi
