#!/bin/sh

# Make sure we’re using the latest Homebrew
echo 'Updating brew...'
brew update

# Upgrade any already-installed formulae
echo 'Upgrading existing formulae...'
brew upgrade


# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."


# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install Bash 4
brew install bash

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep
brew tap josegonzalez/homebrew-php


# Install everything else
brew install ack
brew install git
brew install rename
brew install tree
brew install imagesnap
brew install wget --enable-iri
brew install bash-completion
brew install v8
brew install git-ftp

brew install macvim --override-system-vim
brew install tmux


# Cask applications
# Install Cask (OS X app installer - brew-like)
brew tap phinze/homebrew-cask
brew install brew-cask

# Apps
brew cask install iterm2
brew cask install alfred
brew cask install google-chrome
brew cask install google-chrome-canary
brew cask install caffeine
brew cask install ynab
brew cask install appcleaner
brew cask install evernote
brew cask install plex-home-theater
brew cask install textmate
brew cask install vlc
brew cask install hipchat
brew cask install flux
brew cask install geektool
brew cask install the-unarchiver
brew cask install spectacle
brew cask install copy
brew cask install dropbox
brew cask install droplr
brew cask install mamp


# Remove outdated versions from the cellar
'Running brew cleanup...'
brew cleanup -s

echo 'Running brew doctor...'
brew doctor
