# Bootstrapping
# =============

# Make sure we’re using the latest Homebrew
update
# Upgrade any already-installed formulae
upgrade



# Taps
# ====

# Install more recent versions of some OS X tools
tap homebrew/dupes
# gitsh
tap thoughtbot/formulae
# Cask
tap phinze/homebrew-cask
tap caskroom/versions



# Formulae
# ========

# GNU core utilities (those that come with OS X are outdated)
install coreutils

# GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils

# More recent versions of some OSX tools
install homebrew/dupes/grep

# Python (install this before vim so that it has Python support)
install python

# Git
install git
install git-flow
install gitsh
install hub

# Tools
install wget --enable-iri
install htop
install rsync
install mmv
install direnv

# Gitshots!
install imagesnap

# Node
install node

# Dev tools
install macvim --override-system-vim
install tmux
install reattach-to-user-namespace
install ctags
install ack
install ngrok



# Casks
# =====

# The brew cask command
install brew-cask

# Utils
cask install spectacle
cask install flux
cask install the-unarchiver
cask install caffeine
cask install appcleaner
cask install keyremap4macbook
cask install alfred

# Services
cask install copy
cask install dropbox
cask install evernote

# Developing
cask install mamp
cask install iterm2-nightly
cask install virtualbox
cask install google-chrome-canary
cask install firefox-aurora
cask install opera-next

# Misc
cask install ynab
cask install plex-home-theater
cask install vlc
cask install onepassword

# Communicating
cask install skype
cask install messenger-for-telegram

# QuickLook plugins
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install betterzipql



# Cleanup
# =======

# Link .app applications to ~/Applications
linkapps

# Remove outdated versions from the cellar
cleanup -s

# Check if everything is ok
doctor
